task 0

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,37 +1,43 @@
 #!/usr/bin/env bash
-# Installs Nginx with the following configurations:
-#+    Listens on port 80.
-#+    Returns a page containing "Hello World!" when queried
-#+     at the root with a curl GET request.
-#+    Configures /redirect_me as a "301 Moved Permanently".
-#+    Includes a custom 404 page containing "Ceci n'est pas une page".
-#+    Contains a custom HTTP header named X-Served-By.
-#+    The value of the HTTP header is the hostname of the running server.
+# - Install nginx on my server and customize the starting page
+# - Configure it so that it has a custom HTTP response header
+# - Configure it so that /redirect_me is redirecting to another page (301)
+# - Configure it so that it has a custom 404 error page
 
-apt-get install -y nginx
+sudo apt-get update -y
 
-mkdir -p /var/www/html
-touch /var/www/html/index.html
-echo "Hello World!" > /var/www/html/index.html
-touch /var/www/html/404.html
-echo "Ceci n'est pas une page" > /var/www/html/404.html
+if ! dpkg -l | grep -q "nginx"; then
+	sudo apt-get install nginx -y
+fi
 
-printf %s "server {
-    listen 80 default_server;
-    listen [::]:80 default_server;
-    add_header X-Served-By $HOSTNAME;
-    root   /var/www/html;
-    index  index.html index.htm;
+sudo mkdir -p /etc/nginx/html
+echo "Hello World!" | sudo tee /etc/nginx/html/index.html >/dev/null
 
-    location /redirect_me {
-        return 301 https//YouTube.com/;
-    }
+sudo mkdir -p /etc/nginx/html/error_pages
+echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/error_pages/error_404.html >/dev/null
 
-    error_page 404 /404.html;
-    location /404 {
-      root /var/www/html;
-      internal;
-    }
-}" > /etc/nginx/sites-available/default
+printf "server {
+	listen		80 default_server;
+	listen		[::]:80 default_server;
+	root		/etc/nginx/html;
+	index		index.html;
+	server_name	mywonder.tech;
 
-service nginx restart
+	location / {
+		add_header X-Served-By \"%s\";
+	}
+
+	location /redirect_me {
+		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
+	}
+
+	error_page 404 /error_404.html;
+
+	location = /error_404.html {
+		root	/etc/nginx/html/error_pages;
+		internal;
+	}
+}
+" "$(hostname)" | sudo tee /etc/nginx/sites-available/default >/dev/null
+
+sudo service nginx restart
